-- 056_agent_dashboards.sql — HTML dashboards generated by agents.
-- An agent calls publish_dashboard (MCP tool) → HTML lands here →
-- served publicly at /d/[slug]. The custom_tabs row is managed by the
-- MCP tool, not a DB trigger, so this table is standalone.

create table if not exists aio_control.agent_dashboards (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references aio_control.workspaces(id) on delete cascade,
  business_id uuid references aio_control.businesses(id) on delete cascade,
  label text not null,
  html_content text not null,
  slug text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (slug),
  unique (workspace_id, business_id, label)
);

create index if not exists idx_agent_dashboards_business
  on aio_control.agent_dashboards(business_id);

alter table aio_control.agent_dashboards enable row level security;

drop policy if exists "agent_dashboards_read" on aio_control.agent_dashboards;
create policy "agent_dashboards_read"
  on aio_control.agent_dashboards for select
  using (aio_control.is_workspace_member(workspace_id));

drop policy if exists "agent_dashboards_write" on aio_control.agent_dashboards;
create policy "agent_dashboards_write"
  on aio_control.agent_dashboards for all
  using (aio_control.workspace_role(workspace_id) in ('owner', 'admin', 'editor'));

grant select, insert, update, delete on aio_control.agent_dashboards to authenticated;
grant select, insert, update, delete on aio_control.agent_dashboards to service_role;
